### PR TITLE
WEX support

### PR DESCRIPTION
**Pull request by corpix**
Hello. I have started this(#201) but looks like there is some Qt magic or some secret knowledge I should know about C++ to get this "grep and replace" task working.

First of all, I don't understand why [deletion of the one single translation line](https://github.com/JulyIGHOR/QtBitcoinTrader/commit/8a234727c185eff6eb599c1453d9c560bf32ae22) makes application to segfault. I haven't found any other places than `Norwegian.lng` containing this translation, but it is [in the interface](http://i.imgur.com/YdphGr9.png)! WAT

Second thing is a config signatures. This is a pain to see `The program is corrupted. Download from the official site...` after the build. You probably should have gpg signed binaries, not signed configs because this is inconvenient for contributors. I have disabled https://github.com/JulyIGHOR/QtBitcoinTrader/commit/5110b37b2d4d80492386f7d92a4c11ba27d55643 this check for debuging purpose here.

If somebody would like to build it then you may do it with a [flatpak which I have created](https://github.com/corpix/qt-bitcoin-trader-flatpak/tree/wex) for this application.

### CODE REVIEW

**Comment by JulyIGHOR** [comment]
WEX support is done and now testing, will release it tomorrow.
Signature check is required since we made auto update of those files from server.
Thanks for crash bug report, will inspect it and apply fixes.

**Comment by corpix** [comment]
Ok, if you have the code then this could be closed I think
Thank you

**Comment by JulyIGHOR** [comment]
I can't reproduce crash you reported. Can you please try to clear project and rebuild it again?
Maybe there was old ui moc files there, it should works fine.

**Comment by corpix** [comment]
I have played with this and noticed that https://github.com/corpix/QtBitcoinTrader/commit/7e56b122e053fd7c8b43bc770bbce257ab716d62 HEAD has segfault, but now I don't think that problem is around `.lng` file changes(I have build https://github.com/corpix/QtBitcoinTrader/commit/efa7ef862539b7a8f5416ed8f0e4002d1406a914 HEAD and it has no segfault).
Probably something has been cached while I've been testing, can't find out what... sorry.

**Pull request closed without merging**
